/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lucas.gradesys;

import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;

import com.opencsv.exceptions.CsvException;

public class App {
    public String getGreeting() {
        return "Hello Lucas!";
    }

    public static void main(String[] args) {
        Course course = new Course();
        InputStream inputFileStream = App.class.getClassLoader().getResourceAsStream("Grades.csv");
        try {
            course.loadCourseWorkFromCSV(inputFileStream);
            // Testing:
            System.out.println("Sorted Names: ");
            course.printIncreasingNames();
            System.out.println("Sorted Grades: ");
            course.printIncreasingGrades();
        } catch (IOException | CsvException e) {
            e.printStackTrace();
        }
    }
}
